source 'https://github.com/CocoaPods/Specs.git'
platform :ios, 7.1
xcodeproj 'DataParenting.xcodeproj'
inhibit_all_warnings!
#link_with ['DataParenting', 'DataParentingDev', 'DataParentingTests']

pod 'OpenSSL' # , ' 1.0.200' # 1.0.201 does not compile!
pod 'MBProgressHUD', '~> 0.8'
pod 'SWTableViewCell', '0.3.4'
pod 'Heap', '2.1.3'
pod 'Parse+NSCoding', :git => 'https://github.com/npahucki/Parse-NSCoding.git', :commit => '7ca144edd756eafa4f8bd95fbdfca86bfdd7898a'
pod 'Parse', '1.7.1'
pod 'ParseFacebookUtils', '1.7.1'
pod 'ParseUI', '1.1.3'
pod 'PFCloud+Cache', :git => 'https://github.com/npahucki/PFCloud-Cache.git', :commit => 'c4ed4130b8069a87e9a704d28d0ce5c545b402ca'
#pod 'PFCloud+Cache', :path => '../../PFCloud-Cache/'
pod 'UIActionSheet+Blocks'
pod 'BCGenieEffect', '1.1'
pod 'AppsFlyer-SDK', '2.5.3.11.1'
pod 'RMStore/AppReceiptVerificator', '0.7.1'
pod 'UXCam', '1.0.8'
pod 'Mixpanel', '2.7.2'
#pod 'MBContactPicker', :git => 'https://github.com/npahucki/MBContactPicker.git', :commit => 'b7e7510d21e3e5fdf5f2054bf1775dabb888c412'
pod 'MBContactPicker', '0.1.6'
pod 'CMPopTipView', '2.2'
pod 'CircleProgressBar', :git => 'https://github.com/Eclair/CircleProgressBar', :commit => '310780ae778193944fab1a6d9aafba847b528532'





