platform :ios, 7.0
xcodeproj 'DataParenting.xcodeproj'
inhibit_all_warnings!
#link_with ['DataParenting', 'DataParentingDev', 'DataParentingTests']

pod 'MBProgressHUD', '~> 0.8'
pod 'SWTableViewCell', '0.2.7'
pod 'Heap'
pod 'Parse+NSCoding', :git => 'https://github.com/npahucki/Parse-NSCoding.git', :commit => '322170389c928ba9edddd3402c70b107f24b83b8'
pod 'ParseFacebookUtils', '1.4.0'
pod 'PFCloud+Cache', :git => 'https://github.com/npahucki/PFCloud-Cache.git', :commit => 'b86b8f119e1d9242fc51ac1b683297239ac6e9b7'
pod 'UIActionSheet+Blocks'
pod 'BCGenieEffect', '1.1'
pod 'AppsFlyer-SDK'
pod 'RMStore/AppReceiptVerificator'
pod 'UXCam'





